# Generated by Django 3.0.3 on 2020-02-07 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
